import Gallery from './modules/Gallery';

const galleryImages = [
    'happy-patrons-at hooker-and-eight.jpg',
    'dan-prepping-pizza.jpg',
    'sprinkling-cheese.jpg',
    'steve-on-the-pizza-peel.jpg',
    'pizza-ready-for-the-oven.jpg',
    'pizza-on-pizza-peel.jpg',
    'two-takeaway-pizzas.jpg',
    'calzone-on-plate.jpg',
    'meaty-pizza.jpg',
    'pizza-transferring-to-plate.jpg',
    'steve-prepping-calzone.jpg',
    'adam-enjoying-cleaning.jpg',
    'happy-dan.jpg',
    'fully-loaded-calzone-ready-to-fold.jpg',
    'hooker-and-eight-front-window.jpg',
    'hooker-and-eight-front-at-night.jpg',
    'prepping-mushroom-pizza.jpg',
    'pizza-wheel-cutting.jpg',
    'finishing-with-balsamic-glaze.jpg',
    'hooker-and-eight-owners-and-staff.jpg',
    'this-is-normal.jpg',
    'hooker-and-eight-mirror.jpg',
    'steve-weighing-dough.jpg',
    'rugby-shirt-decoration.jpg',
    'dan-getting-started-on-a-pizza.jpg',
    'dan-showcasing-handmade-doughs.jpg',
    'shaping-the-dough.jpg',
    'vegetable-ingredients.jpg',
    'hooker-and-eight-restaurant-interior.jpg',
    'single-meaty-pizza-for-takeaway.jpg',
    'large-margarita-pizza.jpg',
    'three-pizzas-for-takeaway.jpg',
    'two-pizzas-for-takeaway.jpg',
    'pizzas-in-takeaway-boxes.jpg',
    'meats-and-vegetable-pizza.jpg',
    'meaty-pizzas-for-takeaway.jpg',
    'ready-for-tomato-base.jpg',
]

new Gallery(galleryImages);
